FROM node:14-buster

ENV SDK_FILENAME=commandlinetools-linux-6609375_latest.zip
ENV SDK_CHECKSUM=89f308315e041c93a37a79e0627c47f21d5c5edbe5e80ea8dc0aac8a649e0e92

# java 11
RUN apt-get update && \
    apt-get install -y unzip openjdk-11-jdk-headless ruby2.5 ruby2.5-dev python3-pip locales \
        jed less rsync rclone && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/lib/apt/*

# android sdk tools
RUN cd /tmp && \
    curl --silent -o $SDK_FILENAME https://dl.google.com/android/repository/$SDK_FILENAME && \
    echo -n "$SDK_CHECKSUM  $SDK_FILENAME" | sha256sum  -c && \
    unzip -q $SDK_FILENAME && \
    mkdir -p /android-sdk && \
    mv tools /android-sdk/tools && \
    cd /android-sdk && \
    yes | tools/bin/sdkmanager --sdk_root=/android-sdk --licenses >/dev/null && \
    tools/bin/sdkmanager --sdk_root=/android-sdk \
        "tools" \
        "platform-tools" \
        "platforms;android-29" \
        "build-tools;29.0.3" \
        "extras;google;m2repository" \
        "extras;android;m2repository" && \
    rm -rf /tmp/*

# nativescript
RUN npm install -g nativescript@7.0.11 --unsafe-perm && \
    tns usage-reporting disable && \
    tns error-reporting disable

# segno QR code generator
RUN pip3 install segno

# fastlane (needs ruby2.3 & ruby2.3-dev installed above)
#RUN gem install fastlane -v 2.117.1 -NV
RUN gem install bundle

# fix issue where there is a unicode character in the commit message (also involves install of locales above)
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
RUN locale-gen en_US.UTF-8

ENV ANDROID_HOME=/android-sdk
ENV PATH=/android-sdk/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CMD ["/bin/bash"]
